#!/bin/bash
x=$(($(curl -s https://www.khanacademy.org/profile/icamlearn | grep Profile.init | sed "s/.*points...//" | sed "s/\".*//" | head -c7)-4166122))
y=$(($(curl -s https://www.khanacademy.org/profile/$1 | grep Profile.init | sed "s/.*points...//" | sed "s/\".*//" | head -c7)-$2))
while [[ $(echo $x | sed "s/-//") != $x ]] || [[ $(echo $y | sed "s/-//") != $y ]]; do
x=$(($(curl -s https://www.khanacademy.org/profile/icamlearn | grep Profile.init | sed "s/.*points...//" | sed "s/\".*//" | head -c7)-4166122))
y=$(($(curl -s https://www.khanacademy.org/profile/$1 | grep Profile.init | sed "s/.*points...//" | sed "s/\".*//" | head -c7)-$2))
done
z=$(($x-$y))
w=$(echo $z | sed "s/-//")
a=$([[ $z -lt 0 ]]; echo $?)
b=$(if [[ $a ]]; then echo "ahead"; else echo "behind"; fi)
e=$(if [[ $a ]]; then echo '! :D'; else echo ". D:"; fi)
d=$(ruby -rdate -e "puts Date.parse('$(date +%Y-%m-%d)') - Date.parse('2015-06-23')" | cut -d/ -f1)
p=$((35 * $x / $d))
l=$(($y-$p))
m=$(echo $l | sed "s/-//")
c=$([[ $l -lt 0 ]]&&echo true||echo false)
n=$(if $c; then echo "I need $m points to reach Cam overall."; else echo "I'm $m points ahead in the long run!"; fi)
v=$(($m / 850 + 1))
g=$(($m / 9725 + 1))
i=$(($m / 500 + 1))
r=$([[ $v -eq 1 ]]||echo s)
s=$([[ $g -eq 1 ]]||echo s)
t=$([[ $i -eq 1 ]]||echo s)
echo "Cam has earned | $x points."
echo " I have earned | $y points."
echo "—————————————————————————————————————————"
echo "I'm $b by $w points$e"
echo "—————————————————————————————————————————"
echo "Cam has earned $x points in $d days."
echo "Cam would earn ~$p points in 35 days."
echo $n
if $c; then
echo "—————————————————————————————————————————"
echo "That's $v new video$r,"
echo "$g easy Light-Speed$s,"
echo "or $i Inspiration$t!"
fi
